import { ChangeEvent, FormEvent, useEffect, useRef, useState } from 'react'
import { type Project, type ProjectStatus, type ProjectTheme } from '../data/projects'
import { type HostedStatus, type StudioSnapshot, clearPortfolioOverrides, endStudioSession, hasStudioPassword, hostedLogin, hostedLogout, hostedStatus, isStudioAuthenticated, loadHostedPortfolio, loginStudio, saveHostedPortfolio, savePortfolio, setStudioPassword, snapshotPortfolio, uploadHostedFile } from '../data/portfolioStore'
import CredentialManager from './CredentialManager'
import SecuritySettings from './SecuritySettings'

const statuses: ProjectStatus[] = ['Completed', 'Deployed', 'Working', 'Partially Functional', 'Prototype', 'Under Development', 'Experimental', 'Closed']
const themes: ProjectTheme[] = ['ai', 'agents', 'robotics', 'web', 'creative']

function Skeleton() { return <div className="studio-skeleton" aria-label="Loading portfolio studio"><i /><i /><i /><i /></div> }
function Field({ label, value, onChange, type = 'text', hint }: { label: string; value: string; onChange: (value: string) => void; type?: string; hint?: string }) {
  return <label className="studio-field"><span>{label}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} />{hint && <small>{hint}</small>}</label>
}

function AccessGate({ onSuccess, hosted }: { onSuccess: () => void; hosted: boolean }) {
  const [username, setUsername] = useState(hosted ? 'bittu-bh' : ''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const hasPassword = hasStudioPassword()
  const submit = async (event: FormEvent) => { event.preventDefault(); setError('')
    if (hosted) { const result = await hostedLogin(username, password); if (!result.ok) return setError(result.error || 'Incorrect username or password.'); onSuccess(); return }
    if (!hasPassword && password.length < 8) return setError('Use at least 8 characters.')
    if (!hasPassword && password !== confirm) return setError('Passwords do not match.')
    const ok = hasPassword ? await loginStudio(password) : (await setStudioPassword(password), true)
    if (!ok) return setError('Incorrect password.')
    onSuccess()
  }
  return <main className="studio-gate"><a href="/" className="studio-back">← Return to portfolio</a><section><p className="section-label">Private portfolio studio</p><h1>{hosted || hasPassword ? 'Sign in' : 'Set up your studio'}</h1><p>{hosted ? 'Secure server session. Changes are saved to your hosted portfolio.' : hasPassword ? 'This is a browser-local access gate.' : 'Create a password for this browser before you make portfolio changes.'}</p><form onSubmit={submit}>{hosted && <Field label="Username" value={username} onChange={setUsername} />}<Field label="Password" type="password" value={password} onChange={setPassword} />{!hosted && !hasPassword && <Field label="Confirm password" type="password" value={confirm} onChange={setConfirm} hint="A server-side login is required before publishing this as a real multi-device CMS." />}{error && <p className="studio-error" role="alert">{error}</p>}<button className="btn-primary" type="submit">{hosted || hasPassword ? 'Sign in' : 'Create local studio'}</button></form></section></main>
}

function readFile(event: ChangeEvent<HTMLInputElement>, onRead: (value: string) => void, onError: (value: string) => void) {
  const file = event.target.files?.[0]; if (!file) return
  if (file.size > 1_800_000) return onError('Use an image smaller than 1.8 MB, or add a hosted URL. Large video files need external storage.')
  const reader = new FileReader(); reader.onload = () => onRead(String(reader.result)); reader.onerror = () => onError('This file could not be read.'); reader.readAsDataURL(file)
}

async function readHostedFile(event: ChangeEvent<HTMLInputElement>, onRead: (value: string) => void, onError: (value: string) => void, hosted: boolean) {
  const file = event.target.files?.[0]; if (!file) return
  if (!hosted) return readFile(event, onRead, onError)
  const result = await uploadHostedFile(file)
  if (result.ok && result.url) onRead(result.url); else onError(result.error || 'Upload failed.')
}

export default function PortfolioStudio() {
  const [allowed, setAllowed] = useState(isStudioAuthenticated()); const [loading, setLoading] = useState(true); const [host, setHost] = useState<HostedStatus | null>(null); const [tab, setTab] = useState<'identity' | 'projects' | 'media' | 'credentials' | 'security' | 'all'>('identity'); const [data, setData] = useState<StudioSnapshot>(() => snapshotPortfolio()); const [contentDraft, setContentDraft] = useState(() => JSON.stringify(snapshotPortfolio(), null, 2)); const [selected, setSelected] = useState(0); const [notice, setNotice] = useState(''); const saveTimer = useRef<number | undefined>(undefined)
  useEffect(() => { const timer = window.setTimeout(() => setLoading(false), 350); return () => window.clearTimeout(timer) }, [])
  useEffect(() => { hostedStatus().then(async (status) => { setHost(status); if (status.available && status.configured) { setAllowed(status.authenticated); const saved = await loadHostedPortfolio(); if (saved) setData(saved) } }) }, [])
  const hosted = Boolean(host?.available && host?.configured)
  const update = (next: StudioSnapshot) => { setData(next); window.clearTimeout(saveTimer.current); saveTimer.current = window.setTimeout(async () => { if (hosted) { const result = await saveHostedPortfolio(next); setNotice(result.ok ? 'Saved securely to your hosted portfolio.' : result.error || 'Could not save your hosted changes.') } else setNotice(savePortfolio(next) ? 'Saved locally in this browser preview.' : 'This browser is out of local storage. Use a hosted URL or remove a large image.') }, 350) }
  if (!allowed) return <AccessGate hosted={hosted} onSuccess={() => setAllowed(true)} />
  if (loading) return <main className="studio-page"><Skeleton /></main>
  const project = data.projects[selected]
  const updateProject = (change: Partial<Project>) => update({ ...data, projects: data.projects.map((item, index) => index === selected ? { ...item, ...change } : item) })
  const addProject = () => { const item: Project = { slug: `new-project-${Date.now()}`, title: 'New project', category: 'Project category', theme: 'web', status: 'Prototype', shortDescription: 'Add a short, honest description.', overview: 'Add an editable project overview.', technologies: [], myContribution: [], whatIBuilt: [], media: [] }; const next = { ...data, projects: [...data.projects, item] }; update(next); setSelected(next.projects.length - 1) }
  const removeProject = () => { if (!project || !window.confirm(`Remove “${project.title}” from this browser’s portfolio data?`)) return; const next = { ...data, projects: data.projects.filter((_, index) => index !== selected) }; update(next); setSelected(Math.max(0, selected - 1)) }
  return <main className="studio-page"><header className="studio-header"><a href="/">BK / Portfolio</a><div><span role="status" aria-live="polite">{notice}</span><button className="studio-text-button" onClick={() => { if (hosted) hostedLogout(); else endStudioSession(); setAllowed(false) }}>Sign out</button></div></header><div className="studio-layout"><aside className="studio-sidebar"><p>CONTENT STUDIO</p>{([['identity', 'Contact & links'], ['projects', 'Projects'], ['media', 'Media & resume'], ['credentials', 'Certificates & docs'], ['security', 'Passwords'], ['all', 'All content']] as const).map(([id, label]) => <button key={id} aria-pressed={tab === id} className={tab === id ? 'active' : ''} onClick={() => { setTab(id); if (id === 'all') setContentDraft(JSON.stringify(data, null, 2)) }}>{label}</button>)}{!hosted && <button className="studio-danger" onClick={() => { if (window.confirm('Clear all browser-local studio edits and return to the checked-in portfolio?')) { clearPortfolioOverrides(); window.location.reload() } }}>Reset local edits</button>}</aside><section className="studio-content">
    {tab === 'identity' && <><p className="section-label">Identity & public links</p><h1>Portfolio identity</h1><div className="studio-form-grid"><Field label="Name" value={data.profile.name} onChange={(name) => update({ ...data, profile: { ...data.profile, name } })} /><Field label="Primary positioning" value={data.profile.title} onChange={(title) => update({ ...data, profile: { ...data.profile, title } })} /><Field label="Secondary positioning" value={data.profile.secondaryTitle} onChange={(secondaryTitle) => update({ ...data, profile: { ...data.profile, secondaryTitle } })} /><Field label="Location" value={data.profile.location} onChange={(location) => update({ ...data, profile: { ...data.profile, location } })} /><Field label="Email" type="email" value={data.contact.EMAIL} onChange={(EMAIL) => update({ ...data, contact: { ...data.contact, EMAIL } })} /><Field label="Phone" type="tel" value={data.contact.PHONE} onChange={(PHONE) => update({ ...data, contact: { ...data.contact, PHONE } })} /><Field label="LinkedIn URL" type="url" value={data.contact.LINKEDIN_URL} onChange={(LINKEDIN_URL) => update({ ...data, contact: { ...data.contact, LINKEDIN_URL } })} /><Field label="GitHub URL" type="url" value={data.contact.GITHUB_URL} onChange={(GITHUB_URL) => update({ ...data, contact: { ...data.contact, GITHUB_URL } })} /><Field label="Instagram URL" type="url" value={data.contact.INSTAGRAM_URL} onChange={(INSTAGRAM_URL) => update({ ...data, contact: { ...data.contact, INSTAGRAM_URL } })} /><Field label="YouTube URL" type="url" value={data.contact.YOUTUBE_URL} onChange={(YOUTUBE_URL) => update({ ...data, contact: { ...data.contact, YOUTUBE_URL } })} /><Field label="Hugging Face URL" type="url" value={data.contact.HUGGINGFACE_URL} onChange={(HUGGINGFACE_URL) => update({ ...data, contact: { ...data.contact, HUGGINGFACE_URL } })} /><Field label="Portfolio URL" type="url" value={data.contact.PORTFOLIO_URL} onChange={(PORTFOLIO_URL) => update({ ...data, contact: { ...data.contact, PORTFOLIO_URL } })} /></div></>}
    {tab === 'projects' && <><div className="studio-title-row"><div><p className="section-label">Projects</p><h1>Edit project details</h1></div><button className="btn-primary" onClick={addProject}>Add project</button></div><div className="studio-project-layout"><div className="studio-project-list">{data.projects.map((item, index) => <button className={index === selected ? 'active' : ''} onClick={() => setSelected(index)} key={item.slug}>{item.title}<small>{item.status}</small></button>)}</div>{project && <div className="studio-editor"><Field label="Title" value={project.title} onChange={(title) => updateProject({ title })} /><Field label="Slug" value={project.slug} onChange={(slug) => updateProject({ slug: slug.toLowerCase().replace(/[^a-z0-9-]/g, '-') })} hint="Lowercase letters, numbers and hyphens only." /><Field label="Category" value={project.category} onChange={(category) => updateProject({ category })} /><label className="studio-field"><span>Status</span><select value={project.status} onChange={(event) => updateProject({ status: event.target.value as ProjectStatus })}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><label className="studio-field"><span>Project area</span><select value={project.theme} onChange={(event) => updateProject({ theme: event.target.value as ProjectTheme })}>{themes.map((theme) => <option key={theme}>{theme}</option>)}</select></label><label className="studio-field studio-field--wide"><span>Short description</span><textarea value={project.shortDescription} onChange={(event) => updateProject({ shortDescription: event.target.value })} /></label><label className="studio-field studio-field--wide"><span>Overview</span><textarea value={project.overview} onChange={(event) => updateProject({ overview: event.target.value })} /></label><button className="studio-danger" onClick={removeProject}>Remove project</button></div>}</div></>}
    {tab === 'media' && <><p className="section-label">Media & resume</p><h1>Profile, project media and resume</h1><div className="studio-media-grid"><section><h2>Profile picture</h2>{data.profile.profilePhoto && <img className="studio-avatar" src={data.profile.profilePhoto} alt="Profile preview" />}<label className="studio-upload">Upload image<input type="file" accept="image/*" onChange={(event) => readHostedFile(event, (profilePhoto) => update({ ...data, profile: { ...data.profile, profilePhoto } }), setNotice, hosted)} /></label><Field label="Or profile image URL" value={data.profile.profilePhoto} onChange={(profilePhoto) => update({ ...data, profile: { ...data.profile, profilePhoto } })} /></section><section><h2>Resume</h2><Field label="Resume URL" type="url" value={data.contact.RESUME_URL} onChange={(RESUME_URL) => update({ ...data, contact: { ...data.contact, RESUME_URL } })} hint="Use a real public PDF URL only." /></section><section><h2>Selected project media</h2>{project ? <><label className="studio-upload">Upload image or video<input type="file" accept="image/*,video/mp4,video/webm" onChange={(event) => readHostedFile(event, (source) => updateProject({ media: [{ type: source.match(/\.(mp4|webm)(\?|$)/i) ? 'video' : 'image', source, alt: `${project.title} media`, title: project.title, muted: true, loop: true, playsInline: true }] }), setNotice, hosted)} /></label><Field label={`${project.title} image or video URL`} type="url" value={project.media[0]?.source || ''} onChange={(source) => updateProject({ media: source ? [{ type: source.includes('youtube') ? 'youtube' : source.match(/\.(mp4|webm)(\?|$)/i) ? 'video' : 'image', source, alt: `${project.title} media`, title: project.title, muted: true, loop: true, playsInline: true }] : [] })} hint="Use Cloudinary, YouTube or another hosted URL for videos." /><button className="studio-remove-media" onClick={() => updateProject({ media: [] })}>Remove selected media</button><p className="studio-help">Hosted uploads support files up to 25 MB. Use a video host for larger files.</p></> : <p>Select a project in the Projects tab first.</p>}</section></div></>}
    {tab === 'credentials' && <CredentialManager data={data} hosted={hosted} onChange={update} setNotice={setNotice} />}
    {tab === 'security' && <SecuritySettings hosted={hosted} setNotice={setNotice} />}
    {tab === 'all' && <><p className="section-label">Complete site data</p><h1>Edit all content</h1><p className="studio-help">Edit the complete structured content snapshot, including every project field, education, training and public certificates. Keep the required keys in place. Use Media & resume to upload files.</p><label className="studio-field studio-json-field"><span>Portfolio content (JSON)</span><textarea spellCheck={false} value={contentDraft} onChange={(event) => setContentDraft(event.target.value)} /></label><button className="btn-primary" onClick={() => { try { const parsed = JSON.parse(contentDraft) as StudioSnapshot; if (!parsed.profile || !parsed.contact || !Array.isArray(parsed.projects) || !Array.isArray(parsed.education) || !Array.isArray(parsed.training)) throw new Error('Include profile, contact, projects, education and training.'); parsed.certificates ||= []; update(parsed); setNotice('All content applied and saving…') } catch (error) { setNotice(error instanceof Error ? error.message : 'Invalid JSON.') } }}>Apply all content</button></>}
  </section></div></main>
}
